import javax.swing.*;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowEvent;

public class StartView {
    private JFrame frame;

    private JPanel panelView;
    private JLabel mainMSG;
    private JLabel mainMSG1;
    private JButton mainButton;

    public StartView() {
        frame = new JFrame();
        frame.setSize(575, 350);
        frame.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        frame.add(panelView);

        mainButton.addActionListener(new ButtonAction());

        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panelView = new JPanel();
        panelView.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(3, 2, new Insets(0, 0, 0, 0), -1, -1));
        panelView.setBackground(new Color(-16449406));
        panelView.setFocusable(false);
        Font panelViewFont = this.$$$getFont$$$("OpenDyslexicAlta", Font.BOLD, 36, panelView.getFont());
        if (panelViewFont != null) panelView.setFont(panelViewFont);
        panelView.setPreferredSize(new Dimension(575, 350));
        panelView.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null, TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, null));
        mainMSG1 = new JLabel();
        mainMSG1.setAlignmentX(0.0f);
        mainMSG1.setBackground(new Color(-16449406));
        mainMSG1.setDoubleBuffered(false);
        mainMSG1.setEnabled(true);
        Font mainMSG1Font = this.$$$getFont$$$("OpenDyslexicMono", Font.BOLD, 48, mainMSG1.getFont());
        if (mainMSG1Font != null) mainMSG1.setFont(mainMSG1Font);
        mainMSG1.setForeground(new Color(-657931));
        mainMSG1.setOpaque(true);
        mainMSG1.setRequestFocusEnabled(false);
        mainMSG1.setText("WORD QUIZZLE");
        mainMSG1.setVerticalAlignment(1);
        panelView.add(mainMSG1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(300, 79), null, 0, false));
        mainMSG = new JLabel();
        mainMSG.setBackground(new Color(-16449406));
        Font mainMSGFont = this.$$$getFont$$$("OpenDyslexicMono", Font.BOLD, 48, mainMSG.getFont());
        if (mainMSGFont != null) mainMSG.setFont(mainMSGFont);
        mainMSG.setForeground(new Color(-657931));
        mainMSG.setOpaque(true);
        mainMSG.setText("WELCOME TO");
        mainMSG.setVerticalAlignment(3);
        panelView.add(mainMSG, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_SOUTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(275, 100), null, 0, false));
        mainButton = new JButton();
        mainButton.setAlignmentY(0.0f);
        mainButton.setBackground(new Color(-16734973));
        mainButton.setBorderPainted(true);
        mainButton.setContentAreaFilled(true);
        mainButton.setDefaultCapable(true);
        mainButton.setEnabled(true);
        mainButton.setFocusCycleRoot(false);
        mainButton.setFocusPainted(false);
        Font mainButtonFont = this.$$$getFont$$$("Michroma", Font.BOLD, 20, mainButton.getFont());
        if (mainButtonFont != null) mainButton.setFont(mainButtonFont);
        mainButton.setForeground(new Color(-16777216));
        mainButton.setHorizontalTextPosition(0);
        mainButton.setIconTextGap(4);
        mainButton.setInheritsPopupMenu(true);
        mainButton.setMargin(new Insets(0, 0, 0, 0));
        mainButton.setRequestFocusEnabled(true);
        mainButton.setRolloverEnabled(false);
        mainButton.setSelected(false);
        mainButton.setText("Start");
        mainButton.setVerifyInputWhenFocusTarget(true);
        mainButton.setVisible(true);
        mainButton.putClientProperty("hideActionText", Boolean.FALSE);
        panelView.add(mainButton, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_NORTH, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(100, 60), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panelView;
    }

    public class ButtonAction extends Client implements ActionListener {
        @Override
        public void actionPerformed(ActionEvent e) {
            super.gotoRegLogView();
            frame.dispatchEvent(new WindowEvent(frame, WindowEvent.WINDOW_CLOSING));
        }
    }
}
